### PR TITLE
Big dev merge

### PR DESCRIPTION
**Pull request by axnd**
There are a few different objectives in this pull request that can be broken up if necessary. Those are:
1. Source Map support with the --map option (tested with Google Chrome)
2. Updated dependencies in the package file (a prerequisite for Source Maps, mainly coffeescript)
3. More verbose error logging
4. Changing the way optimize runs uglifyjs2 (setting sequences to false) to fix an issue with Windows Phone 8 throwing exceptions when running the minified JS.

### CODE REVIEW

**Comment by axnd** [comment]
@ylian can you review the changes in here? I've been running the latest version for a couple of weeks so I believe it to be stable enough for release.

**Comment by ylian** [comment]
Published muffin.io 0.1.5 on npm.

**Comment by axnd** [comment]
I don't see the version bump on https://npmjs.org/package/muffin.io

**Comment by ylian** [comment]
The site has a delay. It's there now.

**Pull request merged**
